train_model: True
dataset:
  root: ../../data/semantics
reporting:
  root: .
  csv_path: .
training_params:
  seeds: [60]
  learning_rate: 0.03
  epochs: 1
  batch_size: 2
  root: models
  save_path: model1

