dataset:
  root: ../../data/semantics
reporting:
  root: .
  csv_path: .
encoders: None
training_args:
  do_train: True
  seeds: [50, 60, 70]
  learning_rate: 0.00002  # keep lr small to avoid overfitting
  epochs: 5
  batch_size: 64
  root: models
  save_path: batch_size_32
  max_num_samples_train: 10
  max_num_samples_validation: 10

